# Generated by Django 4.1.7 on 2023-11-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ez_app", "0002_alter_customuser_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("short_name", models.CharField(max_length=20, unique=True)),
                ("total_count", models.IntegerField(default=0)),
                ("remaining_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="seat",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ez_app.seatarea"
            ),
        ),
    ]
