# Generated by Django 4.1.7 on 2023-11-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ez_app", "0003_seatarea_alter_seat_area"),
    ]

    operations = [
        migrations.RemoveField(model_name="seat", name="location",),
        migrations.RemoveField(model_name="seat", name="remaining_count",),
        migrations.RemoveField(model_name="seat", name="total_count",),
    ]
