# Generated by Django 4.1.7 on 2023-11-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ez_app", "0005_seat_event_seatarea_event_alter_ticket_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ez_app.event"
            ),
        ),
        migrations.AlterField(
            model_name="seatarea",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ez_app.event"
            ),
        ),
    ]
