# Generated by Django 4.1.7 on 2023-11-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ez_app", "0006_alter_seat_event_alter_seatarea_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
